### ISSUE TITLE
What is this project about / what will it be about?

### ISSUE THREAD

**Issue by flux627** [Footage-Firm/kafka-ts#3]
Came across this, and was wondering if anyone could give a brief explanation about the intentions of this project.

**Comment by balexander** [comment]
This is a strongly opinionated wrapper around [node-rdkafka](https://github.com/Blizzard/node-rdkafka) and [avro-schema-registry](https://github.com/bencebalogh/avro-schema-registry) that gives an easy way to create new Producers and Consumers. Basically we want to make it very simple for engineers to produce to or consumer from Kafka.

We've just updated the readme and added some example files which should provide some clarity.
